---
title: "college-outcomes"
author: "Ryan Southward"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(skimr)
library(gganimate)
library(gifski)
library(lubridate)
library(ggthemes)
```


```{r, load_data}
raw_data <- read_csv("mrc_table3.csv")

college_and_parent_quintile <- raw_data %>%
  drop_na() %>%
  pivot_longer(
              names_to = c(".value", "quintile"),
              names_pattern = "([a-z0-9_]*)(parq.)",
              cols = c(k_married_cond_parq1:k_married_cond_parq5, k_rank_cond_parq1:k_rank_cond_parq5, ktop1pc_cond_parq1:ktop1pc_cond_parq5) ) %>%
  mutate(quintile = str_sub(quintile, 5, 5)) %>%
  rename("prob_kid_top_one_pct" = ktop1pc_cond_) %>%
  rename("mean_kid_income_ranking" = k_rank_cond_) %>%
  rename("k_married_2014" = k_married_cond_) 

mobility_data <- raw_data %>%
  drop_na() %>%
  pivot_longer(
              names_to = "parent_and_kid_quintile",
              values_to = "prob_based_on_k_par_quintile",
              cols = kq1_cond_parq1:kq5_cond_parq5 ) %>%
  mutate("kid_quintile" = str_sub(parent_and_kid_quintile, 3, 3)) %>%
  mutate("quintile" = str_sub(parent_and_kid_quintile, 14, 14)) 

long_p_quintiles <- raw_data %>%
  drop_na() %>%
  pivot_longer(
              names_to = "quintile",
              values_to = "par_quint_distribution",
              cols = par_q1:par_q5 ) %>%
  mutate(quintile = str_sub(quintile, 6, 6)) 

long_k_quintiles <- raw_data %>%
  drop_na() %>%
  pivot_longer(
              names_to = "kid_quintile",
              values_to = "kid_quint_distribution",
              cols = k_q1:k_q5 ) %>%
  mutate(kid_quintile = str_sub(kid_quintile, 4, 4)) 

long_p_and_q_quints <- inner_join(long_p_quintiles, long_k_quintiles)
  
combined_data <- inner_join(mobility_data, college_and_parent_quintile) 

long_data <- inner_join(combined_data, long_p_and_q_quints) %>%
  select(-c(kq1_cond_parq1:kq5_cond_parq5)) %>%
  select(-c(k_married_cond_parq1:k_married_cond_parq5)) %>%
  select(-c(k_rank_cond_parq1:k_rank_cond_parq5)) %>%
  select(-c(ktop1pc_cond_parq1:ktop1pc_cond_parq5)) %>%
  select(-parent_and_kid_quintile) %>%
  select(-c(par_q1:par_q5, k_q1:k_q5))
  
clean_data <- long_data %>%
  mutate(tier = as.factor(tier)) %>%
  mutate(quintile = as.factor(quintile)) %>%
  mutate(kid_quintile = as.factor(kid_quintile)) %>%
  mutate(type = as.factor(type)) %>%
  mutate(kid_quintile = as.factor(kid_quintile)) %>%
  mutate(iclevel = as.factor(iclevel)) %>%
  mutate(state = as.factor(state)) 



exclude_geo <- combined_data %>%
  select(-c(tier_name, region:multi))
```

```{r}
skim(clean_data)
```


```{r, married_graph_tier}
married_graph_tier <- clean_data %>%
  select(name, tier, k_married, tier_name) %>%
  mutate(tier_name = as.factor(tier_name)) %>%
  drop_na() %>%
  group_by(tier_name) %>%
  summarise(avg_married = mean(k_married)) %>%
  ggplot(aes(x = tier_name, y = avg_married)) +
  geom_col() + 
  labs(title = "Avg. Fraction of Kids Married \nbased on the Tier of their College.",
       subtitle = "Kids from lower-income parents are married \nless frequently.
      Marriges of kids with wealthier parents \nare distributed more evenly.", 
      x = "Tier of Institution",
      y = "Average Fraction Married of a College Tier", 
      caption = "Source: Opportunity Insight.") + 
  coord_flip() + 
  scale_fill_canva() + 
  theme_economist_white()
  
```


```{r}
married_graph_tier
```



```{r}
married_data_parents <- clean_data %>%
  select(name, tier, quintile, k_married_2014, par_toppt1pc) %>%
  drop_na() %>%
  ggplot(aes(x = k_married_2014)) +
  geom_freqpoly() +
  facet_wrap(~quintile) + 
  labs(title = "Distribution of Marrige Rates at a College by Parental Income Quintile.",
       subtitle = "Kids from lower-income parents are married less frequently. \nMarriges of kids with wealthier parents are distributed more evenly.", 
      x = "Percent of kids married.",
      y = "Count", 
      caption = "Source: Opportunity Insight.") +
  theme_tufte()
```

```{r}
married_data_parents
```


```{r, stanford_plot}

mobility_plot_1 <- clean_data %>%
  group_by(name) %>%
  group_by(cohort, .add = TRUE) 

stanford_plot <- clean_data %>%
  filter(name == "Stanford University") %>%
  mutate(kid_quintile = as.integer(kid_quintile))  %>%
  ggplot(aes(x = kid_quintile, y = prob_based_on_k_par_quintile, color = quintile)) +
  geom_jitter() +
  geom_smooth(se = FALSE, method = "loess", formula = y ~ x, span = 1) +
  labs(title = "Likelyhood of a Stanford Student being in a specific Income Quintile based on the Income Quintile of their Parent", 
       subtitle = "No matter the Parent Quintile, Stanford students have a high probability of being in the highest \nincome quintile.",
       x = "Kid Income Quintile",
       y = "Probability", 
       caption = "Source: Opportunity Insight, Graph by Ryan Southward", 
       color = "Parent Income Quintile") +
  transition_time(cohort)+
  labs(title = "Year: {frame_time}") 

animate(stanford_plot, fps=8)
  

```

```{r multi_college_plot}
college_plot <- clean_data %>%
  filter(name == "Stanford University" | name=="Harvard University" | name == "University Of Alabama") %>%
  mutate(kid_quintile = as.integer(kid_quintile))  %>%
  ggplot(aes(x = kid_quintile, y = prob_based_on_k_par_quintile, color = name)) +
  geom_jitter(alpha = .5) +
  geom_smooth(se = FALSE, method = "loess", formula = y ~ x)+
  labs(title = "Probability of Kid Outcome based on Parent Outcome for Different Colleges", 
       subtitle = "Stanford and Harvard are very similar.",
       y = "Probability",
       x = "Kid's Income Quintile Outcome",
       caption = "Source: Opportunity Insight, Graph by Ryan Southward") + 
  transition_time(quintile)+
   transition_states(
    quintile,
    transition_length = 5,
    state_length = 3
  ) + 
  labs(title = "Parent Quintile: {closest_state}. 1 is the lowest, 5 is the highest.") 

# geom_ribbon(aes(ymin = 0,ymax = predict(loess(prob_based_on_k_par_quintile ~ kid_quintile))),
               # alpha = 0.3,fill = "red") 
  
animate(college_plot)
```

